-- MySQL Script generated by MySQL Workbench
-- 10/05/15 22:14:00
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ordemdeservico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ordemdeservico` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ordemdeservico` ;

-- -----------------------------------------------------
-- Table `ordemdeservico`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordemdeservico`.`Fornecedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `cnpj` CHAR(14) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordemdeservico`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordemdeservico`.`Clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Cpf` VARCHAR(11) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Endereco` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Cpf_UNIQUE` (`Cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordemdeservico`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordemdeservico`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `idFornecedor` INT NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `preco` FLOAT NOT NULL,
  `Clientes_id` INT NULL,
  PRIMARY KEY (`idProduto`),
  INDEX `fk_Produto_Fornecedor_idx` (`idFornecedor` ASC),
  INDEX `fk_Produto_Clientes1_idx` (`Clientes_id` ASC),
  CONSTRAINT `fk_Produto_Fornecedor`
    FOREIGN KEY (`idFornecedor`)
    REFERENCES `ordemdeservico`.`Fornecedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_Clientes1`
    FOREIGN KEY (`Clientes_id`)
    REFERENCES `ordemdeservico`.`Clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordemdeservico`.`ProdutoPeca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordemdeservico`.`ProdutoPeca` (
  `qualidade` VARCHAR(100) NOT NULL,
  `quantidade` INT NOT NULL,
  `idProduto` INT NOT NULL,
  INDEX `fk_ProdutoPeca_Produto1_idx` (`idProduto` ASC),
  CONSTRAINT `fk_ProdutoPeca_Produto1`
    FOREIGN KEY (`idProduto`)
    REFERENCES `ordemdeservico`.`Produto` (`idProduto`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ordemdeservico`.`ProdutoServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ordemdeservico`.`ProdutoServico` (
  `idProduto` INT NOT NULL,
  `tempoReparo` FLOAT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  INDEX `fk_ProdutoServico_Produto1_idx` (`idProduto` ASC),
  CONSTRAINT `fk_ProdutoServico_Produto1`
    FOREIGN KEY (`idProduto`)
    REFERENCES `ordemdeservico`.`Produto` (`idProduto`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
