/*
 * ------------Software Ordem de Serviço----------
 * Linguagem de Programação 2 - 1ºSem/2015
 * Profº Joinville - UFGD
 * Alunos: Felipe G. / Gustavo T. / Reinaldo
 */
package br.com.os.interfaces;

import br.com.os.controle.ControladorFornecedor;
import br.com.os.entidade.Fornecedor;
import br.com.os.entidade.Visão;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo
 */
public class JanelaCadastrarFornecedores extends javax.swing.JInternalFrame {

    /**
     * Creates new form JanelaCadastrarFornecedores
     */
    ControladorFornecedor controlador;
    Vector<Visão<String>> fornecedores_cadastrados;
    DefaultListModel lista;

    public JanelaCadastrarFornecedores(ControladorFornecedor controlador) {
        this.controlador = controlador;
        fornecedores_cadastrados = Fornecedor.getVisões();

        JanelaPrincipal.getDeskpPanelPrincipal().add(this).setVisible(true);

        initComponents();
        inicializaDados();
        lista = (DefaultListModel) listFornecedores.getModel();
        Vector<Visão<String>> visoes = Fornecedor.getVisões();
        for (Visão<String> elemento : visoes) {
            lista.addElement(elemento);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelFornecedores = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        labelCnpj = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        labelID = new javax.swing.JLabel();
        txtCnpj = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        buttonInserir = new javax.swing.JButton();
        buttonAlterar = new javax.swing.JButton();
        buttonRemover = new javax.swing.JButton();
        buttonLimpar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listFornecedores = new javax.swing.JList();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Cadastrar / Alterar Fornecedores");

        labelFornecedores.setText("Lista dos Fornecedores");

        labelNome.setText("Nome:");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        labelCnpj.setText("Cnpj:");

        txtId.setEditable(false);

        labelID.setText("ID:");

        buttonInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/os/images/add1-24.png"))); // NOI18N
        buttonInserir.setText("Inserir");
        buttonInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInserirActionPerformed(evt);
            }
        });

        buttonAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/os/images/edit24.png"))); // NOI18N
        buttonAlterar.setText("Alterar");
        buttonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAlterarActionPerformed(evt);
            }
        });

        buttonRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/os/images/close24.png"))); // NOI18N
        buttonRemover.setText("Remover");
        buttonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoverActionPerformed(evt);
            }
        });

        buttonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/os/images/rename24.png"))); // NOI18N
        buttonLimpar.setText("Limpar");
        buttonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(buttonInserir)
                .addGap(18, 18, 18)
                .addComponent(buttonAlterar)
                .addGap(18, 18, 18)
                .addComponent(buttonRemover)
                .addGap(18, 18, 18)
                .addComponent(buttonLimpar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonInserir)
                    .addComponent(buttonAlterar)
                    .addComponent(buttonRemover)
                    .addComponent(buttonLimpar))
                .addGap(20, 20, 20))
        );

        listFornecedores.setModel(new DefaultListModel());
        listFornecedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                evento(evt);
            }
        });
        jScrollPane2.setViewportView(listFornecedores);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(labelFornecedores)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(labelID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId)
                        .addGap(18, 18, 18)
                        .addComponent(labelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelCnpj)
                        .addGap(18, 18, 18)
                        .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(labelFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNome)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelID))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCnpj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void buttonInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInserirActionPerformed
        inserirFornecedor(evt);    }//GEN-LAST:event_buttonInserirActionPerformed

    private void buttonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAlterarActionPerformed
        alterarFornecedor(evt);
    }//GEN-LAST:event_buttonAlterarActionPerformed

    private void buttonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoverActionPerformed
        removerFornecedor(evt);
    }//GEN-LAST:event_buttonRemoverActionPerformed

    private void buttonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimparActionPerformed
        limparFornecedor(evt);
    }//GEN-LAST:event_buttonLimparActionPerformed

    private void evento(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_evento
        consultarFornecedor(evt);
    }//GEN-LAST:event_evento

    private void inicializaDados() {
        txtId.setText(String.valueOf(Fornecedor.ultimoSequencial() + 1));

    }

    private Visão<String> getVisõesFornecedoresCadastrados(String chave) {
        for (Visão<String> visão : fornecedores_cadastrados) {
            if (visão.getChave().equals(chave)) {
                return visão;
            }
        }
        return null;
    }

    private Fornecedor obtemFornecedor() {

        Integer id = Integer.parseInt(txtId.getText());

        String nome = txtNome.getText();
        if (nome.isEmpty()) {
            return null;
        }

        String cnpj = txtCnpj.getText();
        if (cnpj.isEmpty()) {
            return null;
        }

        return new Fornecedor(id, nome, cnpj);

    }

    private void inserirFornecedor(java.awt.event.ActionEvent evt) {
        Fornecedor fornecedor = obtemFornecedor();
        String msg_erro = null;
        if (fornecedor != null) {
            msg_erro = controlador.inserirFornecedor(fornecedor);
        } else {
            msg_erro = "Algum atributo nao informado";
        }
        if (msg_erro == null) {
            Visão<Integer> visao = fornecedor.getVisão();
            lista.addElement(visao);
                            JOptionPane.showInternalMessageDialog(this, "Fornecedor inserido com sucesso.");

        } else {
            JOptionPane.showMessageDialog(this, msg_erro, "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void limparFornecedor(java.awt.event.ActionEvent evt) {

        txtNome.setText("");
        txtCnpj.setText("");
        txtId.setText(String.valueOf(Fornecedor.ultimoSequencial() + 1));

        listFornecedores.setSelectedIndex(0);

    }

    private void consultarFornecedor(java.awt.event.MouseEvent evt) {
        Visão<String> visão = (Visão<String>) listFornecedores.getSelectedValue();
        Fornecedor fornecedor = null;
        String msg_erro = null;
        if (visão != null) {
            fornecedor = Fornecedor.buscarFornecedor(Integer.parseInt(visão.getChave()));
            if (fornecedor == null) {
                msg_erro = "Fornecedor nao encontrado";
            }

        }
        if (msg_erro == null) {
            txtId.setText(String.valueOf(fornecedor.getVisão().getChave()));
            txtCnpj.setText(fornecedor.getCnpj());
            txtNome.setText(fornecedor.getNome());

        } else {
            JOptionPane.showMessageDialog(this, msg_erro, "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void removerFornecedor(java.awt.event.ActionEvent evt) {
        Visão<String> visão = (Visão<String>) listFornecedores.getSelectedValue();
        String msg_erro = null;
        if (visão != null) {
            msg_erro = controlador.removerFornecedor(Integer.parseInt(visão.getChave()));
        } else {
            msg_erro = "Fornecedor nao encontrado";
        }
        if (msg_erro == null) {
            fornecedores_cadastrados.remove(visão);
            lista.removeElement(visão);
                            JOptionPane.showInternalMessageDialog(this, "Fornecedor removido com sucesso.");


        } else {
            JOptionPane.showMessageDialog(this, msg_erro, "ERRO", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void alterarFornecedor(java.awt.event.ActionEvent evt) {
        Fornecedor fornecedor = obtemFornecedor();
        String msg_erro = null;
        if (fornecedor != null) {
            msg_erro = controlador.alterarFornecedor(fornecedor);
        } else {
            msg_erro = " Algum atributo nao informado";
        }
        if (msg_erro == null) {
            Visão<String> visão = getVisõesFornecedoresCadastrados(String.valueOf(fornecedor.getId()));
            if (visão != null) {
                visão.setInfo(fornecedor.getVisão().getInfo());
                listFornecedores.updateUI();
                listFornecedores.setSelectedValue(visão,true);
                JOptionPane.showInternalMessageDialog(this, "Fornecedor alterado com sucesso.");
                

            }
        } else {
            JOptionPane.showMessageDialog(this, msg_erro, "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAlterar;
    private javax.swing.JButton buttonInserir;
    private javax.swing.JButton buttonLimpar;
    private javax.swing.JButton buttonRemover;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCnpj;
    private javax.swing.JLabel labelFornecedores;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelNome;
    private javax.swing.JList listFornecedores;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
